### ISSUE TITLE
AV_PIX_FMT_RGB24 or AV_PIX_FMT_BGR24

### ISSUE THREAD

**Issue by TonyZhu2015** [sipsorcery-org/SIPSorceryMedia.FFmpeg#29]
Hi Team,

I am learning the source code of FFmpegVideoEncoder. On line 444. for _i420ToRgb converter, the target PixelFormat is AV_PIX_FMT_**BGR**24 instead of AV_PIX_FMT_RGB24. This baffles me if I correct this by changing it to AV_PIX_FMT_RGB24 to be consistent. The video is blue washed(showing blue). Can you help me understand this?

_i420ToRgb = new VideoFrameConverter(
                                width, height,
                                AVPixelFormat.AV_PIX_FMT_YUV420P,
                                width, height,
                                AVPixelFormat.AV_PIX_FMT_BGR24);

Appreciate it,

Regards,
Rong Zhu

**Comment by ChristopheI** [comment]
Hi @TonyZhu2015 ,

It's because in FFmpeg library **AV_PIX_FMT_BGR24** format is equivalent to **PixelFormat.Format24bppRgb** [format](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.pixelformat?msclkid=7e0af028cf6311ecafd2a420650bef5f&view=dotnet-plat-ext-6.0) used to manage Bitmap 

For example
```
Bitmap bmpImage = new Bitmap(width, height, stride, PixelFormat.Format24bppRgb, sample);
```

**Comment by TonyZhu2015** [comment]
Thanks very much. I will close this issue
