### ISSUE TITLE
FFMpeg binaries are not embedded anymore

### ISSUE THREAD

**Issue by jeremyVignelles** [sipsorcery-org/SIPSorceryMedia.FFmpeg#42]
The documentation states :

> No additional steps are required for an x64 build. The nuget package includes the [FFmpeg](https://www.ffmpeg.org/) x64 binaries.

This does not seem to be true since v1.0.

I get that embedding ffmpeg in the package is heavy and that there is no point in embedding it, but this sentence should be removed and replaced with a way to download ffmpeg.

**Comment by ChristopheI** [comment]
> I get that embedding ffmpeg in the package is heavy and that there is no point in embedding it, but this sentence should be removed and replaced with a way to download ffmpeg.

Exactly. I will update the README when I will release a new version of this package.

**Comment by jeremyVignelles** [comment]
FYI : this is how we did to package libvlc in NuGet packages for use in LibVLCSharp: https://github.com/mfkl/libvlc-nuget

**Comment by lostmsu** [comment]
Is there a separate compatible installable package for the binaries? Just faced some issues using a 3rd party ffmpeg installation on Windows.

**Comment by ChristopheI** [comment]
I'm using this site:
https://www.gyan.dev/ffmpeg/builds/
https://github.com/GyanD/codexffmpeg/releases/

**Comment by maticcavalleri** [comment]
@ChristopheI What about on Linux (specifically I'm using Raspbian on RPI4)? I find the package is working good on Windows (using FFMpeg Binaries provided in the repository) but these same binaries do not work on Linux. I'm guessing because they are only there for Windows. I tried using different FFMpeg builds such as static-arm64-ffmpeg 6.0 build but with no luck. I am getting "unable to load DLL 'avdevice.58'".

I think that which binaries to use for specific build should be updated. I also tried with "sudo apt install ffmpeg" on linux and providing path to that but with no luck. Same error as with previous step. Error gets raised on FFmpegInit.Initialise method.

**Comment by rob-baily** [comment]
I updated the README in #60 to give the link for where to download for Windows and take away the statement that they are embedded.  BTW this project is built on top of https://github.com/Ruslan-B/FFmpeg.AutoGen which provides the actual interface to FFMPEG so maybe that will help although currently this is tied to version 4.4 of FFMPEG before the pull request goes (if it does).  This link may also be useful https://ffmpeg.org/download.html.

**Comment by jeremyVignelles** [comment]
Closing as completed
